package com.kz.sme_management;

import com.github.javafaker.Faker;
import com.kz.sme_management.dto.customer.AddAddressDto;
import com.kz.sme_management.model.Employee;
import com.kz.sme_management.model.sale.PaymentMethod;
import com.kz.sme_management.model.customer.Customer;
import com.kz.sme_management.model.product.*;
import com.kz.sme_management.repository.contract.CartRepository;
import com.kz.sme_management.repository.contract.ContractRepository;
import com.kz.sme_management.repository.customer.AddressRepository;
import com.kz.sme_management.repository.customer.CustomerRepository;
import com.kz.sme_management.repository.employee.EmployeeRepository;
import com.kz.sme_management.repository.product.*;
import com.kz.sme_management.service.contract.CartItemDto;
import com.kz.sme_management.service.contract.ContractDTO;
import com.kz.sme_management.service.contract.ContractService;
import com.kz.sme_management.service.customer.impl.CustomerService;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@SpringBootApplication
@RequiredArgsConstructor
public class SmeManagementApplication {

    private final ContractRepository contractRepository;
    private final CartRepository cartRepository;
    private final EmployeeRepository employeeRepository;
    private final ContractService contractService;
    private final AddressRepository addressRepository;
    private final CustomerRepository customerRepository;
    private final CustomerService customerService;
    private final BrandRepository brandRepository;
    private final ProductRepository productRepository;
    private final CategoryRepository categoryRepository;
    private final SizeRepository sizeRepository;
    private final TypeRepository typeRepository;


    public static void main(String[] args) {
        SpringApplication.run(SmeManagementApplication.class, args);
    }

    @Bean
    CommandLineRunner initDatabase() {
        return args ->
        {
            categoryRepository.save(new Category("BEYAZ EŞYA"));
            categoryRepository.save(new Category("MOBİLYA"));
            categoryRepository.save(new Category("AKSESUAR"));
            categoryRepository.save(new Category("TEKSTİL"));

            typeRepository.save(new Type("BAZA"));
            typeRepository.save(new Type("YEMEK ODASI TAKIMI"));
            typeRepository.save(new Type("OTURMA GRUBU"));
            typeRepository.save(new Type("DOLAP"));
            typeRepository.save(new Type("MUTFAK MASA SANDALYE TAKIMLARI"));
            typeRepository.save(new Type("GENÇ ODASI"));
            typeRepository.save(new Type("AADENEME"));
            typeRepository.save(new Type("YATAK ODASI TAKIMI"));
            typeRepository.save(new Type("BERJER"));
            typeRepository.save(new Type("BAŞLIK"));
            typeRepository.save(new Type("KANEPE"));
            typeRepository.save(new Type("SANDALYE"));
            typeRepository.save(new Type("MASA"));
            typeRepository.save(new Type("GENÇ ODASI TAKIMI"));
            typeRepository.save(new Type("TV SEHPASI"));
            typeRepository.save(new Type("AÇIK HAVA MOBİLYALARI"));
            typeRepository.save(new Type("SEHPALAR"));
            typeRepository.save(new Type("BAZA SETİ"));
            typeRepository.save(new Type("LAMBADERLER"));
            typeRepository.save(new Type("PLAZMA ÜNİTESİ DUVAR ÜNİTESİ"));
            typeRepository.save(new Type("ŞİFONYER"));
            typeRepository.save(new Type("KÖŞE TAKIMI"));
            typeRepository.save(new Type("ABAJURLAR"));
            typeRepository.save(new Type("KONSOL"));
            typeRepository.save(new Type("BEŞİK"));
            typeRepository.save(new Type("PORTMANTO"));
            typeRepository.save(new Type("ÇALIŞMA MASASI"));
            typeRepository.save(new Type("YAŞAM ODASI TAKIMI"));
            typeRepository.save(new Type("KİTAPLIK"));
            typeRepository.save(new Type("BENÇ"));
            typeRepository.save(new Type("GENÇ ODASI SANDALYELERİ"));
            typeRepository.save(new Type("YASTIK"));
            typeRepository.save(new Type("ASKI"));
            typeRepository.save(new Type("BAHÇE TAKIMI"));
            typeRepository.save(new Type("DRESUAR-AYNA"));
            typeRepository.save(new Type("BEBEK ODASI TAKIMI"));
            typeRepository.save(new Type("EKMEKLİK"));
            typeRepository.save(new Type("KOMODİN"));
            typeRepository.save(new Type("PUF & TV KOLTUKLARI"));
            typeRepository.save(new Type("YATAK"));
            typeRepository.save(new Type("AYAKKABILIK"));
            typeRepository.save(new Type("ADET"));
            typeRepository.save(new Type("AKSESUAR"));
            typeRepository.save(new Type("KUMAŞ"));
            typeRepository.save(new Type("VİTRİN"));
            typeRepository.save(new Type("FİSKOS"));
            typeRepository.save(new Type("YORGAN"));
            typeRepository.save(new Type("KOMİDİN"));
            typeRepository.save(new Type("KIRLENT"));
            typeRepository.save(new Type("EV TEKSTİLİ"));
            typeRepository.save(new Type("RANZA"));
            typeRepository.save(new Type("ALEZ"));
            typeRepository.save(new Type("MASASI"));
            typeRepository.save(new Type("BALKON MOBİLYASI"));
            typeRepository.save(new Type("TAKIMI"));
            typeRepository.save(new Type("PUF"));
            typeRepository.save(new Type("TV SEHPALARI"));

            brandRepository.save(new Brand("AHMUR", 40, 70, 65, 100, 7.5));
            brandRepository.save(new Brand("ARNO", 30, 50, 45, 100, 7.5));
            brandRepository.save(new Brand("BELLONA", 2, 40, 30, 100, 7.5));
            brandRepository.save(new Brand("EKOL", 20, 50, 45, 100, 7.5));
            brandRepository.save(new Brand("ERTAŞ", 10, 50, 45, 100, 7.5));
            brandRepository.save(new Brand("İMAJ MOBİLYA", 30, 60, 55, 100, 7.5));
            brandRepository.save(new Brand("LUXEV", 30, 60, 55, 100, 7.5));
            brandRepository.save(new Brand("ÖNDER", 0, 60, 55, 100, 7.5));
            brandRepository.save(new Brand("RAHAT", 0, 50, 45, 100, 7.5));
            brandRepository.save(new Brand("VESPERO", 0, 50, 45, 100, 7.5));
            brandRepository.save(new Brand("YEŞİLEGE", 0, 25, 25, 100, 7.5));

            sizeRepository.save(new Size("100 CM"));
            sizeRepository.save(new Size("120 CM"));
            sizeRepository.save(new Size("130 CM"));
            sizeRepository.save(new Size("140 CM"));
            sizeRepository.save(new Size("150 CM"));
            sizeRepository.save(new Size("160 CM"));
            sizeRepository.save(new Size("180 CM"));
            sizeRepository.save(new Size("200 CM"));
            sizeRepository.save(new Size("90 CM"));
            sizeRepository.save(new Size("100 X 190"));
            sizeRepository.save(new Size("100 X 200"));
            sizeRepository.save(new Size("120 X 190"));
            sizeRepository.save(new Size("120 X 200"));
            sizeRepository.save(new Size("130 X 190"));
            sizeRepository.save(new Size("140 X 190"));
            sizeRepository.save(new Size("140 X 200"));
            sizeRepository.save(new Size("150 X 190"));
            sizeRepository.save(new Size("150 X 200"));
            sizeRepository.save(new Size("160 X 190"));
            sizeRepository.save(new Size("160 X 200"));
            sizeRepository.save(new Size("180 X 200"));
            sizeRepository.save(new Size("200 X 200"));
            sizeRepository.save(new Size("50 X 90"));
            sizeRepository.save(new Size("60 X 120"));
            sizeRepository.save(new Size("70 X 110"));
            sizeRepository.save(new Size("70 X 120"));
            sizeRepository.save(new Size("70 X 130"));
            sizeRepository.save(new Size("70 X 140"));
            sizeRepository.save(new Size("75 X 160"));
            sizeRepository.save(new Size("80 X 130"));
            sizeRepository.save(new Size("80 X 180"));
            sizeRepository.save(new Size("80 X 190"));
            sizeRepository.save(new Size("80 X 200"));
            sizeRepository.save(new Size("90 X 190"));
            sizeRepository.save(new Size("90 X 200"));
            sizeRepository.save(new Size("90 X 185"));


            productRepository.save(new Product("BELL_26PSXHH", "PESARO S BAŞLIK", 2346, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("150 CM").get()));
            productRepository.save(new Product("51ORD60", "ORLANDO KOLTUK TAKIMI (3+2+B+B)", 33795.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("BELL_28BLLE5", "BELLA BAZA", 3498.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("120 X 190").get()));
            productRepository.save(new Product("AHMR_PORTO04", "PORTO KOMODİN (2 ADET)", 2350, brandRepository.findByName("AHMUR").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("22LSS3304Y0Y0", "LARISSA ZİGON SEHPA", 4132.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("BELL_28FROE6", "FIERO BAZA", 5005.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("ARNO_TREND07", "GENÇ TREND ŞİFONYER", 3014, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7820", "NEW GOLDEN BAZA 160*200", 5993.62087956463, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("EKOL_E-7831", "NATURAL BAŞLIK 150 LİK FÜME", 2864, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get()));
            productRepository.save(new Product("59VLL9900", "VELLA MİNİ TAKIM", 14751.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("AÇIK HAVA MOBİLYALARI").get()));
            productRepository.save(new Product("20MRS4S", "Marses Sehpa", 1924.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("BELL_27VSP02002000H00", "VALERIA SLEEP", 4837, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("200 X 200").get()));
            productRepository.save(new Product("EKOL_E-1577", "EKOL TV SEHPASI", 530, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("TV SEHPASI").get()));
            productRepository.save(new Product("ARNO_KARŞIYAKA31", "KARŞIYAKA Komodin", 1087, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_MOSTAR18", "MOSTAR KÖŞE PLUS", 20390, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("EKOL_E-6206", "TESLA YATAK 180*200", 7078, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get()));
            productRepository.save(new Product("BELL_28VRSI5", "VERSO-S BAZA AYAKSIZ", 5150.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("160 X 190").get()));
            productRepository.save(new Product("22MTG3005LDFW", "Montego Dolap Modülü", 2286.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("PLAZMA ÜNİTESİ DUVAR ÜNİTESİ").get()));
            productRepository.save(new Product("VESP_ARMANİ53", "ARMANİ MİDİ KÖŞE PLUS", 23355, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("RAHAT_YALIN04", "YALIN 3+3+ 1+1", 20420, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("RAHAT_ELAGANCE21", "ELAGANCE SET", 8530, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA SETİ").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("29VIO9950", "VIOLA TEKLİ (2 ADET)", 6131.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("AÇIK HAVA MOBİLYALARI").get()));
            productRepository.save(new Product("22VAA30053X4A", "Valencia Dolap Modülü", 1763, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("PLAZMA ÜNİTESİ DUVAR ÜNİTESİ").get()));
            productRepository.save(new Product("BELL_28VZTI6", "VİENZA BAZA", 3961, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("160 X 200").get()));
            productRepository.save(new Product("EKOL_E-7586", "TESLA BAŞLIK 150 LİK FÜME", 1898, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get()));
            productRepository.save(new Product("VESP_MARİN COOL15", "MARİN COOL BAZA", 3575, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("59MSK9901", "MOZAIK OVAL MASA TAKIMI", 30935.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("AÇIK HAVA MOBİLYALARI").get()));
            productRepository.save(new Product("22LOR2550NGNG", "LOREN KONSOL", 6301.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_DRM-257", "MELODİ BERJER", 2948, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("22LEY2400XZXZ", "LENY MAKYAJ AYNASI", 671.6, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_SAFİR05", "SAFİR TEKLİ", 3170, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("VESP_ROYAL16", "ROYAL TEKLİ", 3000, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("ERTAS_DELON14", "DELON ÜÇLÜ", 14541, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("ERTAS_BİBLO30", "BİBLO YATAK ODASI TAKIMI", 37788, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("22LSS2100Y0Y0", "LARISSA MAKYAJ MASASI", 7360.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("22ALZ2209A1A1", "ALVIS 180 LİK KARYOLA KASASI", 3173.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_PEARL05", "GENÇ PEARL ŞİFONYER AYNASI", 1326, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_MERLİN10", "MERLİN TEKLİ PLUS", 3930, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("LUX_ARMA22", "ARMA 3+3+1 TAKIM", 30763, brandRepository.findByName("LUXEV").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("ERTAS_CAVANİ22", "CAVANİ ORTA RAF", 515, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("29ROV9952", "ROVER SEHPA", 3141.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("AÇIK HAVA MOBİLYALARI").get()));
            productRepository.save(new Product("BELL_27AFC00901900400", "AURA FRESH CLEAN", 4682.6, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("ARNO_RÖNESANS27", "GENÇ RÖNESANS KOMODİN", 1780, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("22ANR2001OPFI", "ANDERA SÜRGÜ KAPAKLI GARDIROP", 19550, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_26HESGG01", "HENA-S BAŞLIK", 746, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("140 CM").get()));
            productRepository.save(new Product("BELL_26LNSFF", "LİNDA-S BAŞLIK", 2245.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("130 CM").get()));
            productRepository.save(new Product("EKOL_E-5564", "ANGEL AHŞAP RANZA CEVİZ 90*190", 5930, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("RANZA").get()));
            productRepository.save(new Product("VESP_ORİX02", "ORİX ÜÇLÜ YATAKLI", 5076, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("BELL_27OFF01202000800", "OFFSET FORM", 4682.6, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("İMAJ25", "NOWAY GOLD ARA SEHPA", 3640, brandRepository.findByName("İMAJ MOBİLYA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("LUX_İKON32", "İKON TEK KAPILI DOLAP CAM KAPAK", 5370, brandRepository.findByName("LUXEV").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_27ORP00701400200", "ORIENT PLUS", 1735.6, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("70 X 140").get()));
            productRepository.save(new Product("EKOL_E-7041", "LİVZA ÇOK AMAÇLI DOLAP", 2356, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("DOLAP").get()));
            productRepository.save(new Product("EKOL_E-7136", "MELODİ KONSOL AYNASI ( BÜYÜK )", 728, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KONSOL").get()));
            productRepository.save(new Product("BELL_27CAP01802000200", "CAPRİCE", 3903.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("180 X 200").get()));
            productRepository.save(new Product("VESP_DOUBLE14", "DOUBLE COMFORT YATAK", 6070, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("140 X 190").get()));
            productRepository.save(new Product("51MRSCK", "MARSES V KÖŞE", 22800.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KÖŞE TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7834", "NATURAL BAŞLIK 160 LIK FÜME", 3150, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get()));
            productRepository.save(new Product("VESP_DREAM36", "DREAM LİFE BAZA SETİ", 12950, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA SETİ").get(), sizeRepository.findByName("150 X 200").get()));
            productRepository.save(new Product("ARNO_PEARL10", "GENÇ PEARL KARYOLA BAŞLIĞI (100)", 1520, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("22MNS2203VOD0", "MONTES 120 LİK KARYOLA KASASI", 3646.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("51LFT53", "LOFTY KOLTUK TAKIMI (3+B)", 14453.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("EKOL_E-6923", "LİNDA BENCH (SIRTSIZ) FÜME", 1598, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BENÇ").get()));
            productRepository.save(new Product("BELL_27ORY00802000200", "ORIENT PLUS YOUNG", 2343.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("80 X 200").get()));
            productRepository.save(new Product("RAHAT_DERİN04", "DERİN KANEPE", 8490, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("LUX_PRADA15", "PRADA YATAK ODASI BAZALI", 40378, brandRepository.findByName("LUXEV").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7080", "TERRA SÜRGÜLÜ DOLAP", 16644, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("DOLAP").get()));
            productRepository.save(new Product("23VZL61590230002", "VILZA 6159 SANDALYE (2 ADET) (Alternatif)", 4310.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_KARŞIYAKA32", "KARŞIYAKA Sürme Kapılı Dolap (200x210)", 10505, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("RAHAT_VİSİON22", "VİSİON SET", 11075, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA SETİ").get(), sizeRepository.findByName("150 X 200").get()));
            productRepository.save(new Product("ARNO_LUNA13", "LUNA Tv Sehpası Üst Modül Uzun", 1610, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("52GTA1616ZEXZ", "GRAVITA 6 KAPAKLI YATAK ODASI TK. (150/160 BAŞLIKLI)", 52222.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_26HESII01", "HENA-S BAŞLIK", 798, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("160 CM").get()));
            productRepository.save(new Product("22VZL2228OPO6", "VILZA 120 LİK BAŞLIK", 2257.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("51CNT86", "CANTONA KÖŞE TAKIMI (Köşe+Berjer)", 15061.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KÖŞE TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-6583", "MELODİ KOMODİN AYTAŞI", 1593, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KOMODİN").get()));
            productRepository.save(new Product("VESP_DREAM24", "DREAM LİFE BAZA PEDLİ", 3480, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("ERTAS_MAJESTIC06", "MAJESTIC MASA", 9966, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("22MIS2400OPOP", "MISTRAL MAKYAJ AYNASI", 946.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("ERTAS_PORTRE29", "PORTRE ORTA SEHPA SETİ", 11088, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_NEHİR07", "NEHİR Konsol", 7950, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("RAHAT_LEONİ24", "LEONİ SET", 11802, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA SETİ").get(), sizeRepository.findByName("180 X 200").get()));
            productRepository.save(new Product("22VLO27001R1R", "VALESCO VİTRİN", 6644.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7780", "PRO ACTİVE BAŞLIK 150 LİK FÜME", 1871.22063020408, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get()));
            productRepository.save(new Product("20SVT3E", "Sanvito Üçlü", 11459.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("BELL_27RFK00802000600", "REFLEKS", 2628.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("80 X 200").get()));
            productRepository.save(new Product("22LCD2700ZE3I", "LUCIDA VİTRİN", 6026.1, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_27GLC01002000400", "GOLDEN COMFORT", 5068, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("100 X 200").get()));
            productRepository.save(new Product("20ATT4S", "Atlanta Köşe Sehpa", 3320.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("EKOL_DRM-400", "VİCTORİA KANEPE", 13116, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("İMAJ45", "RİVERS PLUS BERJER", 4745, brandRepository.findByName("İMAJ MOBİLYA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("VESP_SPRİNG18", "POWER SPRİNG BAZA", 3155, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("51MNO50", "MONACO KOLTUK TAKIMI (3+3+B+B)", 21896.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("BELL_27AAP01802000H00", "ANTI AGING PRIME", 5722.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("180 X 200").get()));
            productRepository.save(new Product("RAHAT_SAFRAN04", "SAFRAN 3+3+1+1", 24460, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("ARNO_FOREST29", "FOREST Dolapsız Yatak Odası Takımı", 19100, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_26HESMM", "PETRA PLUS S BAŞLIK", 1450, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("200 CM").get()));
            productRepository.save(new Product("VESP_AYDA04", "AYDA 3+3+1+1 PLUS", 20520, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("22MAA3306FSFS", "MARIANA YAN SEHPA", 2990, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("BELL_26ESYMM", "ESTONYA BAŞLIK", 4427.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("200 CM").get()));
            productRepository.save(new Product("AHMR_RİO01", "RİO YATAK ODASI TAKIMI", 17000, brandRepository.findByName("AHMUR").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("22ANR3400OPFI", "ANDERA KİTAPLIK", 5218.1, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_OSCAR44", "OSCAR KÖŞE TAKIM PLUS (3+3)", 18745, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("RAHAT_İNCİ03", "İNCİ BAŞLIK", 1100, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("EKOL_E-7068", "MANASTIR KİTAPLIK", 2432, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KİTAPLIK").get()));
            productRepository.save(new Product("51VDA30", "VELDA OTURMA GRUBU (3+1)", 9909.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("BELL_28LNCB5", "LİNDA-S BAZA", 2936.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("ERTAS_DELON03", "DELON ŞİFONYER+AYNA", 7256, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("52BLS3110FSOP", "BELISSA SÜRGÜ KAPAKLI (Başlıklı)", 17309.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_CİTY01", "GENÇ CİTY 4 Kapılı Dolap", 9720, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("22ALO2100CWCZ", "ALEGRO MAKYAJ MASASI", 4476.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("RAHAT_LAVİTA09", "LAVİTA BAŞLIK", 1445, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("ARNO_NEHİR08", "NEHİR Konsol + Konsol Aynası + Açılır Masa + 6 Sandalye", 24647, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_ARMONİ17", "ARMONİ Sandalye", 2378, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("22PZA3302P1P2", "PLAZA ORTA SEHPA", 5881.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("AKSESUAR").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("22RNT3176AVBS", "RENTO AÇILIR MASA", 4507.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("MUTFAK MASA SANDALYE TAKIMLARI").get()));
            productRepository.save(new Product("EKOL_E-6931", "MİNÖR ORTA SEHPA CEVİZ", 524, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("VESP_MERCAN04", "MERCAN TEKLİ PLUS", 3295, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("BELL_27BKD01802000400", "BLACK DIAMOND", 11242.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("180 X 200").get()));
            productRepository.save(new Product("BELL_27AFC01001900400", "AURA FRESH CLEAN", 5059.1, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("100 X 190").get()));
            productRepository.save(new Product("EKOL_E-7583", "TESLA BAŞLIK 120 LİK FÜME", 1548, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get()));
            productRepository.save(new Product("EKOL_E-7708", "SERENİTY YATAK 160*200 KAHVE", 5405.92758816, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get()));
            productRepository.save(new Product("ARNO_STAR02", "STAR Çift Kişilik Amortisörlü Karyola (160)", 9725, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7561", "NEW MODA BAZA 90*190 FÜME", 2951, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("VESP_NEHİR015", "NEHİR YATAKLI ÜÇLÜ PLUS", 11225, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("ERTAS_CANANİ12", "CAVANİ KARYOLA", 8790, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_NEHİR012", "NEHİR YATAKLI ÜÇLÜ", 10825, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("29GLR9954", "GLORY MASA", 8824.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("AÇIK HAVA MOBİLYALARI").get()));
            productRepository.save(new Product("20HRY5R", "Henry Uzanmalı Köşe", 10631.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KÖŞE TAKIMI").get()));
            productRepository.save(new Product("22VZL2004OPFM", "VILZA 4 KAPAKLI GARDIROP", 14230.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7756", "BALANCE YATAK 100*200 KAHVE", 4203.73132752381, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get()));
            productRepository.save(new Product("EKOL_DRM-399", "VİCTORİA KOLTUK TAKIMI (3+3+1)", 29532, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("VESP_LUSSO04", "LUSSO BAŞLIK", 2400, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("160 X 200").get()));
            productRepository.save(new Product("VESP_RİSTA06", "RİSTA TEKLİ PLUS", 3180, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("VESP_ASOS44", "ASOS BAZA SETİ", 11475, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA SETİ").get(), sizeRepository.findByName("150 X 200").get()));
            productRepository.save(new Product("RAHAT_VİCTOR02", "VİCTOR KANEPE", 9090, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("ERTAS_MAJESTIC35", "MAJESTIC ŞİFONYER+AYNA", 12506, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_26HENII", "PETRA PLUS BAŞLIK", 1287.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("160 CM").get()));
            productRepository.save(new Product("BELL_27NSR00801900200", "NON STRESS RELAX", 2250, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("80 X 190").get()));
            productRepository.save(new Product("29ATA9950", "ATLAS TEKLİ", 3219.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("AÇIK HAVA MOBİLYALARI").get()));
            productRepository.save(new Product("VESP_İCON04", "İCON 3+3+1 (PLUS)", 24820, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("ARNO_LİLYUM09", "LİLYUM Yatak Odası Takımı Sürme Kap.D. (Başlıklı)", 35737, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_ALAÇATI11", "ALAÇATI 3+3+1+1 TAKIM", 20810, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("22TWI37560000", "TWIN CİBİNLİK", 1618.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BEBEK ODASI TAKIMI").get()));
            productRepository.save(new Product("RAHAT_MİRA13", "MİRA KANEPE", 8900, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("22ARL2226K05F", "ARLES 90/100 LUK BAŞLIK", 1303.6, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("ERTAS_DENEME007", "AADENEME", 111100, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("AADENEME").get()));
            productRepository.save(new Product("ARNO_CİTY14", "GENÇ CİTY Şifonyer Aynası", 1311, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_28FLEB5", "FLEXY BAZA BAŞLIK TAKIMI", 4260.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("52VAA16163X4A", "VALENCIA 6 KAPAKLI YATAK ODASI TK. (150/160 BAŞLIKLI)", 26974.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_LUNA06", "Luna Şifonyer Aynası", 2402, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("22VAA34003X40", "VALENCIA KİTAPLIK", 4221.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_27CPC01602000700", "COPPERTECH COOLER", 9362.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("160 X 200").get()));
            productRepository.save(new Product("22SDY2009FDZV", "SANDY SÜRGÜ KAPAKLI GARDIROP", 8891.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_RANZA12", "90*190 Ayrılabilir Ranza / Yüksek Montessori Karyola AltıYatağı", 1824, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("22MNO2300A19G", "MONACO KOMODİN (1 ADET)", 1079, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("22ARL2101JGJH", "ARLES ŞİFONYER", 2703.6, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-6404", "PERGE YATAK 160*200", 6072, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get()));
            productRepository.save(new Product("ARNO_FLASH19", "GENÇ FLASH KOMODİN", 1572, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_27VSP00801800H00", "VALERIA SLEEP", 2391, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("80 X 180").get()));
            productRepository.save(new Product("VESP_LUXURY03", "LUXURY BAŞLIK", 1860, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("150 X 200").get()));
            productRepository.save(new Product("20SVL7J", "Sanvela Köşe Kollu Uzanmalı Sol", 7907.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KÖŞE TAKIMI").get()));
            productRepository.save(new Product("VESP_ASOS24", "ASOS BAZA", 4910, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("150 X 200").get()));
            productRepository.save(new Product("EKOL_E-6957", "SİDELYA SANDALYE ADET ( SİYAH )", 948, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SANDALYE").get()));
            productRepository.save(new Product("22ALZ2300A1SO", "ALVIS KOMODİN (1 ADET)", 1261.6, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_DURU15", "GENÇ DURU 3 Kapılı Dolap", 9039, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("RAHAT_REİNA15", "REİANA BAŞLIK", 1819, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("160 X 200").get()));
            productRepository.save(new Product("VESP_İSKANDİNAV11", "İSKANDİNAV 3+3+1+1", 18390, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("LUX_SÜRPRİZ17", "SÜRPRİZ KOLTUK TAKIMI 3+3+1+1", 37268, brandRepository.findByName("LUXEV").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("RAHAT_FERAH02", "FERAH KANEPE", 7190, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("EKOL_E-6433", "MARSİLYA BAŞLIK 100 LÜK KAHVE", 748, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get()));
            productRepository.save(new Product("BELL_27NOS01602000200", "NO STRESS (RELAXTIC)", 5204.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("160 X 200").get()));
            productRepository.save(new Product("VESP_GOLD63", "GOLD FULL ORTOPEDİK YATAK", 3300, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("140 X 190").get()));
            productRepository.save(new Product("BELL_26VZSEE", "VİENZA-S BAŞLIK", 1424, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("120 CM").get()));
            productRepository.save(new Product("EKOL_E-7138", "MATHİLDA KONSOL AYNASI ( ADET )", 684, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KONSOL").get()));
            productRepository.save(new Product("BELL_28NRLC5", "NATURAL LINEN BAZA", 2503.1, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("100 X 190").get()));
            productRepository.save(new Product("VESP_EVA13", "EVA TEKLİ", 2916, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("ERTAS_JAGUAR21", "JAGUAR ALT BLOK :", 4894, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_RELAX21", "RELAX PLUS YATAK", 6095, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("EKOL_E-7140", "SAHRA KONSOL AYNASI ( ADET )", 790, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KONSOL").get()));
            productRepository.save(new Product("VESP_LUSSO01", "LUSSO BAŞLIK", 2150, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("51APD53", "ADEN PLUS KOLTUK TAKIMI (3+B)", 12556.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("EKOL_E-7539", "NEW VALERİA BAZA 150*200", 5548, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("51MRSCM", "MARSES KÖŞE TAKIMI (V Köşe+Berjer)", 27071.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KÖŞE TAKIMI").get()));
            productRepository.save(new Product("AHMR_LONDRA03", "LONDRA YATAK ODASI TAKIMI ŞİFONYER", 3700, brandRepository.findByName("AHMUR").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("51ORD53", "ORLANDO KOLTUK TAKIMI (3+B)", 17859.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("51ATTAI", "ATLANTA KÖŞE ASIMETRİK SOL+D TAKIM", 29197, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KÖŞE TAKIMI").get()));
            productRepository.save(new Product("BELL_27GLS01601900H00", "GOLDEN SMART", 4212, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("160 X 190").get()));
            productRepository.save(new Product("BELL_27ORY00701300200", "ORIENT PLUS YOUNG", 1745.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("70 X 130").get()));
            productRepository.save(new Product("BELL_27HND01401900200", "HENA DREAM", 2256.1, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("140 X 190").get()));
            productRepository.save(new Product("22ALO2244CWCW", "ALEGRO 90 LIK BAZALI KARYOLA", 3416.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("52LSS1516Y0Y0", "LARISSA 5 KAPAKLI YATAK ODASI TK. (150/160 BAŞLIKLI)", 36612.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("22CRN2400ZEZE", "CARLINO MAKYAJ AYNASI", 1435.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_UZAY09", "GENÇ UZAY KARYOLA BAŞLIĞI (100)", 1714, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("23MIT1080H6H6", "MIRANTE YUVARLAK PUF", 1078.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("51TNA72", "TİNA KÖŞE TAKIMI (Uzanmalı Köşe+Berjer)", 13074.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KÖŞE TAKIMI").get()));
            productRepository.save(new Product("ARNO_LİKYA33", "LİKYA Açılır Masa", 4711, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_FABIO03", "FABIO Karyola Başlığı", 2927, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_LUNA19", "LUNA Sandalye", 1980, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("ERTAS_CANANİ16", "CAVANİ BAZALI YATAK ODASI TAKIMI", 34826, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7705", "SERENİTY YATAK 150*200 KAHVE", 4914.4796256, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get()));
            productRepository.save(new Product("23LTT63210220002", "LORETTO 6321 SANDALYE (2 ADET) (Alternatif)", 4344.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("22INR3400FMFD", "INTRO KİTAPLIK", 3841.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("22VLO31571R1R", "VALESCO ALTERNATİF AÇILIR YEMEK MASASI", 6065.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_STYLE29", "STYLE SPORT YATAK", 2040, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("ERTAS_BİBLO23", "BİBLO 3 LÜ", 13182, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("VESP_İLARE03", "İLARE BAŞLIK", 1795, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("BELL_27NRL00801800400", "NATURAL LINEN", 3921.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("80 X 180").get()));
            productRepository.save(new Product("ARNO_LUNA12", "LUNA Tv Ünitesi Uzun", 6504, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-6883", "ZERAFET YAŞAM ÜNİTESİ LEDLİ", 4088.8, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("TV SEHPASI").get()));
            productRepository.save(new Product("BELL_28NRLH6", "NATURAL LINEN BAZA", 4165.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("150 X 200").get()));
            productRepository.save(new Product("BELL_26HESFF", "PETRA PLUS S BAŞLIK", 1058.1, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("130 CM").get()));
            productRepository.save(new Product("VESP_DOUBLE04", "DOUBLE COMFORT BAŞLIK", 2700, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("160 X 200").get()));
            productRepository.save(new Product("BELL_26VZSKK", "VİENZA-S BAŞLIK", 1926, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("180 CM").get()));
            productRepository.save(new Product("VESP_BLUE STAR13", "BLUE STAR YATAK", 4010, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("VESP_İCON01", "İCON 3+3+1", 23930, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("BELL_28VRCH6", "VERSO BAZA", 3719, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("150 X 200").get()));
            productRepository.save(new Product("22GTA2234ZE1U", "GRAVITA 180 LİK BAŞLIK", 6421, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("20SVL4A", "Sanvela Puf", 2825.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KÖŞE TAKIMI").get()));
            productRepository.save(new Product("22LTT30052V2V", "Loretto Dolap Modülü", 2234.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("PLAZMA ÜNİTESİ DUVAR ÜNİTESİ").get()));
            productRepository.save(new Product("EKOL_E-501", "EKOL E-501 3 TEKERLEKLİ ORTA SEHPA", 1500, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("ERTAS_PUMA22", "PUMA D.ÜNİTESİ :", 7991, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_Montessori14", "Montessori Yüksek", 6325, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BEBEK ODASI TAKIMI").get()));
            productRepository.save(new Product("RAHAT_SANDRA16", "SANDRA YATAK", 4008, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("180 X 200").get()));
            productRepository.save(new Product("BELL_28FROC6", "FIERO BAZA", 4547.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("100 X 200").get()));
            productRepository.save(new Product("BELL_26PTRMM", "PETRA BAŞLIK", 2800.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("200 CM").get()));
            productRepository.save(new Product("BELL_26HESII", "PETRA PLUS S BAŞLIK", 1287.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("160 CM").get()));
            productRepository.save(new Product("VESP_MARİN COOL23", "MARİN COOL BAŞLIK", 2280, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("150 X 200").get()));
            productRepository.save(new Product("RAHAT_FERAH01", "FERAH BERJER", 3440, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("ARNO_NEHİR09", "NEHİR Konsol aynası", 1295, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7697", "SERENİTY BAZA 100*200 KAHVE", 3419.86171237447, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("EKOL_E-6909", "GOLDY 2 KAPILI DOLAP", 2732.96, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("DOLAP").get()));
            productRepository.save(new Product("BELL_27BMS00801800400", "BELLA MASTER SLEEP", 4629.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("80 X 180").get()));
            productRepository.save(new Product("BELL_27CAP01002000200", "CAPRİCE", 2184.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("100 X 200").get()));
            productRepository.save(new Product("BELL_26PTRBB", "PETRA BAŞLIK", 1562.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("90 CM").get()));
            productRepository.save(new Product("ERTAS_COOL28", "COOL ORTA SEHPA", 3321, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("ARNO_FOREST08", "FOREST Şifonyer", 4020, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("20FNX1C", "Fonte Berjer", 4537.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("24NCLTK", "NICOLY MUTFAK MASA SETİ", 9771.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("MUTFAK MASA SANDALYE TAKIMLARI").get()));
            productRepository.save(new Product("VESP_ALOEVERA39", "ALOEVERA FRESH SLEEP YATAK", 3085, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("EKOL_E-7646", "COMFORT BAZA 150*200 FÜME", 4796.48919431293, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("EKOL_E-7620", "VİSCO ROYAL YATAK 90*190", 5762.10153619048, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get()));
            productRepository.save(new Product("EKOL_E-7513", "NEW MODA BAŞLIK 160 LIK BEYAZ", 1127, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get()));
            productRepository.save(new Product("EKOL_E-6074", "TESLA BAZA 160*200", 6085, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("AHMR_RİO07", "RİO KONSOL", 5000, brandRepository.findByName("AHMUR").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("RAHAT_CLASS30", "CLASS FULL SET", 12270, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA SETİ").get(), sizeRepository.findByName("180 X 200").get()));
            productRepository.save(new Product("ARNO_CROSS05", "GENÇ CROSS ŞİFONYER AYNASI", 952, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-6686", "DORA KOMODİN BEYAZ", 836, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KOMİDİN").get()));
            productRepository.save(new Product("22INR2003FMFD", "INTRO 3 KAPAKLI GARDIROP", 7605.1, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("22LEY2226NYNY", "LENY 90/100 LÜK BAŞLIK", 1661.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("AHMR_DENEME001", "AADENEME", 166700, brandRepository.findByName("AHMUR").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("AADENEME").get()));
            productRepository.save(new Product("LUX_SHELL10", "SHELL TV ÜNİTESİ", 2500, brandRepository.findByName("LUXEV").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7618", "VİSCO ROYAL BAZA 90*190", 3152.6043893748, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("BELL_27CPC02002000700", "COPPERTECH COOLER", 11104.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("200 X 200").get()));
            productRepository.save(new Product("22SEA3400TWJ3", "SELINA KİTAPLIK", 4382.6, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_26PSXKK", "PESARO S BAŞLIK", 2567, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get(), sizeRepository.findByName("180 CM").get()));
            productRepository.save(new Product("ARNO_LİKYA53", "GENÇ LİKYA/URLA/SOFT Merdivenli Ranza Karyola Altı", 2352, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("RAHAT_CAROL04", "CAROL YATAK", 2146, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("100 X 200").get()));
            productRepository.save(new Product("VESP_ELENA03", "ELENA 3+3+1+1 PLUS", 21744, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("23MTG61660230001", "MONTEGO 6166 SANDALYE (2 ADET)", 6297.1, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("22ORD3304AYOB", "ORLANDO ZİGON SEHPA", 3026.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("AKSESUAR").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("52GTA6001ZEXZ", "GRAVITA YEMEK ODASI TAKIMI", 42558.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("22MNR2232PHPH", "MONREAL 150 / 160 LIK BAŞLIK", 2509.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("20CRN3D", "Carlino Üçlü", 13182.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("ARNO_FLASH34", "FLASH MINI GENÇ MISTY 150 LİK BAŞLIK", 2076, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7597", "PERGE YATAK 180*200", 6900.337806, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get()));
            productRepository.save(new Product("22BLS3200FSOP", "BELISSA ÇALIŞMA MASASI", 4130.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_27BEA00901900H00", "BIOENERGY ACTIVE", 3638.6, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("BELL_27SSP01601900700", "SOFT SELECTION PRO-5", 6115.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("160 X 190").get()));
            productRepository.save(new Product("EKOL_E-7719", "SERENİTY BAZA 120*200 BEYAZ", 4146.20402296728, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("ERTAS_DELON10", "DELON KONSOL + AYNA", 11679, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_URLA26", "Urla 75*160 Büyüyen Beşik", 2403, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BEŞİK").get(), sizeRepository.findByName("75 X 160").get()));
            productRepository.save(new Product("EKOL_E-7842", "NATURAL BAZA 160*200 KAHVE", 7568, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("22CRN2001ZEZE", "CARLINO SÜRGÜ KAPAKLI GARDIROP", 22746.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_28VLRF5", "VALERIA BAZA", 4454, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("130 X 190").get()));
            productRepository.save(new Product("23NRM63120220001", "NORM SANDALYE (2 Adet)", 3571.1, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("MUTFAK MASA SANDALYE TAKIMLARI").get()));
            productRepository.save(new Product("51SVLCJ", "SANVELA V KÖŞE", 22220, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KÖŞE TAKIMI").get()));
            productRepository.save(new Product("22ALO2237CWCW", "ALEGRO 160 LIK BAZALI KARYOLA", 5879.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_ARMONİ14", "ARMONİ Konsol", 7563, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("22MIT3155HXHX", "MIRANTE AÇILIR YEMEK MASASI (Alternatif)", 8230.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("52PMO2701", "PALERMO TV ÜNİTESİ", 6302.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("PLAZMA ÜNİTESİ DUVAR ÜNİTESİ").get()));
            productRepository.save(new Product("59GLR9900", "GLORY MİNİ TAKIM", 21824.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("AÇIK HAVA MOBİLYALARI").get()));
            productRepository.save(new Product("EKOL_E-6721", "FREZYA ORTA SEHPA BEYAZ MERMER NİKELAJ", 1490, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("BELL_27CPS01802000400", "COPPERTECH SMART", 9144.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("180 X 200").get()));
            productRepository.save(new Product("RAHAT_VİSİON24", "VİSİON SET", 13290, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA SETİ").get(), sizeRepository.findByName("180 X 200").get()));
            productRepository.save(new Product("ARNO_FLASH22", "GENÇ FLASH KARYOLA ALTI", 2642, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_DİEGO06", "DİEGO TEKLİ PLUS", 3980, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("ERTAS_DELON04", "DELON KOMODİN(2 ADET)", 5634, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("52MNO1616A19G", "MONACO 6 KAPAKLI YATAK ODASI TK. (150/160 BAŞLIKLI)", 21488.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_BODRUM01", "BODRUM 3+3+1+1", 22512, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("ERTAS_JAGUAR17", "JAGUAR KONSOL + AYNA", 7461, brandRepository.findByName("ERTAŞ").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_SOFT16", "GENÇ SOFT Karyola (100)", 4802, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("ARNO_RÖNESANS07", "RÖNESANS TV Ünitesi", 7679, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("22LNT3315ZGZG", "LANTES ZİGON SEHPA", 1759.2, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("22VZL3006OPFM", "Vilza Yan Modül", 5167.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("PLAZMA ÜNİTESİ DUVAR ÜNİTESİ").get()));
            productRepository.save(new Product("EKOL_E-7737", "BALANCE YATAK 100*200 FÜME", 4203.73132752381, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get()));
            productRepository.save(new Product("20ECT1W", "Efect Tekli Sağ Cepli", 5390.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("22NPL3321BABA", "NAPOLİ DRESUAR AYNASI", 1141.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("AKSESUAR").get(), typeRepository.findByName("DRESUAR-AYNA").get()));
            productRepository.save(new Product("EKOL_E-7017", "VENEDİK YAŞAM ÜNİTESİ", 5304.8, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("TV SEHPASI").get()));
            productRepository.save(new Product("ARNO_DURU07", "Duru 75*160 Büyüyen Beşik Takım", 5304, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BEŞİK").get(), sizeRepository.findByName("75 X 160").get()));
            productRepository.save(new Product("AHMR_LONDRA08", "LONDRA TV ÜNİTESİ", 5150, brandRepository.findByName("AHMUR").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("VESP_ENERGY39", "SMART ENERGY PEDLİ YATAK", 2975, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("120 X 200").get()));
            productRepository.save(new Product("EKOL_DRM-410", "FRİDA BERJER", 3648, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("20MRS4A", "Marses Puf", 2497, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("OTURMA GRUBU").get()));
            productRepository.save(new Product("22SEA2203TWTW", "SELINA 120 LİK KARYOLA KASASI", 3418.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_28TWKB6", "TWINJOY BAZA", 1430, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("90 X 200").get()));
            productRepository.save(new Product("ARNO_FOREST07", "FOREST Aynalı Kapak", 1974, brandRepository.findByName("ARNO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK ODASI TAKIMI").get()));
            productRepository.save(new Product("22ANR2700OPFI", "ANDERA VİTRİN", 7572.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-6865", "CHERRY KONSOL AYNASIZ", 6672.8, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KONSOL").get()));
            productRepository.save(new Product("BELL_28VEIG6", "VENISA BAZA", 3083.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("140 X 200").get()));
            productRepository.save(new Product("52LOR2702", "LOREN TV ÜNİTESİ", 8147.8, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("PLAZMA ÜNİTESİ DUVAR ÜNİTESİ").get()));
            productRepository.save(new Product("VESP_DOUBLE16", "DOUBLE COMFORT YATAK", 6625, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("160 X 200").get()));
            productRepository.save(new Product("23GTA63150230001", "GRAVITA 6315 SANDALYE (2 ADET)", 5438.4, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("EKOL_E-7083", "TERRA SANDIKLI BAZA 160*200", 5168, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get()));
            productRepository.save(new Product("22NCLTK", "NICOLY MUTFAK MASA SETİ", 11516.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("MUTFAK MASA SANDALYE TAKIMLARI").get()));
            productRepository.save(new Product("22MEN2226FS0B", "MENTY 90/100 LÜK BAŞLIK", 2031.9, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("22ALO3205CWCZ", "ALEGRO ÇALIŞMA MASASI KİTAPLIĞI", 2741.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("GENÇ ODASI TAKIMI").get()));
            productRepository.save(new Product("22LFT3312LSLS", "LOFTY YAN SEHPA", 968.5, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("SEHPALAR").get()));
            productRepository.save(new Product("RAHAT_VİSİON02", "VİSİON BAZA", 2800, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("22CRN2700ZEFW", "CARLINO VİTRİN", 8749.3, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YEMEK ODASI TAKIMI").get()));
            productRepository.save(new Product("BELL_27CPC00902000700", "COPPERTECH COOLER", 6128, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("90 X 200").get()));
            productRepository.save(new Product("RAHAT_SAFRAN02", "SAFRAN KANEPE", 8790, brandRepository.findByName("RAHAT").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("KANEPE").get()));
            productRepository.save(new Product("EKOL_E-7717", "SERENİTY BAŞLIK 100 LÜK BEYAZ", 1056.07766878523, brandRepository.findByName("EKOL").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAŞLIK").get()));
            productRepository.save(new Product("VESP_STYLE23", "STYLE SPORT FULL SET", 6285, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BAZA SETİ").get(), sizeRepository.findByName("90 X 190").get()));
            productRepository.save(new Product("BELL_27AFC01201900400", "AURA FRESH CLEAN", 5997.7, brandRepository.findByName("BELLONA").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("120 X 190").get()));
            productRepository.save(new Product("VESP_PUKKA11", "PUKKA TEKLİ PLUS", 4410, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("BERJER").get()));
            productRepository.save(new Product("VESP_ALOEVERA47", "ALOEVERA FRESH SLEEP YATAK PEDLİ", 4015, brandRepository.findByName("VESPERO").get(), categoryRepository.findByName("MOBİLYA").get(), typeRepository.findByName("YATAK").get(), sizeRepository.findByName("150 X 200").get()));


            Faker faker = new Faker();

            List<Customer> customers = new ArrayList<>();
            for (int i = 0; i < 100; i++) {
                try {
                    String code = Integer.toString(faker.number().numberBetween(15_000, 99_000));
                    String tc = Integer.toString(faker.number().numberBetween(1_000_000_00, 2_000_000_000));

                    Customer customer = new Customer(code, faker.name().fullName(), tc, faker.phoneNumber().cellPhone(), faker.internet().emailAddress());
                    customer.setDetails(faker.lorem().sentence());
                    customers.add(customer);
                } catch (Exception exception) {
                    System.out.println(exception);
                }
            }
            customerRepository.saveAll(customers);

            Customer customer = customerRepository.findAll().get(0);
            AddAddressDto addAddressDto = null;
            for (int i = 0; i < 4; i++) {
                addAddressDto = new AddAddressDto();
                addAddressDto.setCity(faker.address().city());
                addAddressDto.setDetails(faker.address().fullAddress());
                addAddressDto.setDistrict(faker.address().state());
                addAddressDto.setName("Ev Adresi - " + (i + 1));
                customerService.addAddress(addAddressDto, customer.getId());
            }


            Employee employee = new Employee(null, "Hüsnü", "Şanal");
            Employee e = employeeRepository.save(employee);

            CartItemDto cartItemDto = new CartItemDto(productRepository.findAll().get(0).getId(), 3, 123.0, new Date(System.currentTimeMillis()));
            ContractDTO contractDto = new ContractDTO(customer.getId(), addressRepository.findAll().get(0).getId(), e.getId(), List.of(cartItemDto), PaymentMethod.CASH);
            contractService.save(contractDto);
        };
    }
}
